name: Backend Pipeline

on:
  push:
    branches: ['main']

permissions:
  id-token: write
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - account-service
          - auth-service
          - transaction-service

    env:
      REGISTRY: depaulacr.azurecr.io
      RESOURCE_GROUP: de_paul_RG
      CLUSTER_NAME: depaulaks

    steps:
    
    - name: Checkout repo
      uses: actions/checkout@v3
      

    - name: 'Login to Azure using OIDC'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 


    - name: ACR login via Azure CLI (OIDC)
      run: az acr login --name depaulacr


    - name: Set AKS Context
      run: |
          az aks get-credentials --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME --overwrite-existing


    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

        
    - name: Install dependencies
      run: npm ci
      working-directory: ./backend/${{ matrix.service }}


    - name: Run tests
      run: npm test
      working-directory: ./backend/${{ matrix.service }}


    - name: Build Docker image
      run: |
          docker build -t $REGISTRY/${{ matrix.service }}:latest ./backend/${{ matrix.service }}

    
    - name: Push Docker image
      run: |
          docker push $REGISTRY/${{ matrix.service }}:latest


    - name: Deploy to AKS
      run: |
          kubectl apply -f ./backend/${{ matrix.service }}/k8s/dev/deployment.yaml
          kubectl apply -f ./backend/${{ matrix.service }}/k8s/dev/service.yaml  