name: Backend Pipeline

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - account-service
          - auth-service
          - transaction-service

    steps:
    
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

        
    - name: Install dependencies
      run: npm ci
      working-directory: ./backend/${{ matrix.service }}

    - name: Run tests
      run: npm test
      working-directory: ./backend/${{ matrix.service }}



